name: Publish Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Debug Package JSON
        run: |
          cat package.json
          echo "Current directory contents:"
          ls -la

      - name: Install Dependencies
        run: npm ci

      - name: Compile TypeScript
        run: npm run compile

      - name: Package Extension
        run: npx vsce package

      - name: Publish to VS Code Marketplace
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
        run: |
          echo "Publishing extension..."
          npx vsce publish -p $VSCE_TOKEN || echo "Publication failed"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.vsix
          draft: false
          prerelease: false
